[metadata]
name = nftlist-lists
version = 0.1.0
description = IP address lists for popular services
long_description = file: README.md
long_description_content_type = text/markdown
author = Mateusz Piwek
author_email = barnaba@200ms.net
url = https://github.com/tools200ms/nftlist-lists
classifiers =
    License :: OSI Approved :: MIT License
    Operating System :: POSIX :: Linux
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.6+

[options]
include_package_data = True
python_requires = >=3.6
zip_safe = False

[options.data_files]
/var/lib/nftlist = data/*
