version: '3.8'

services:
  package-builder:
    build: .
    container_name: package-builder
    volumes:
      - ./build_packages.sh:/build/build_packages.sh:ro  # Share script (read-only)
      - ../pkgs:/build/dist  # Share built packages
      - ../nftlist-lists/data:/build/data:ro  # Share package content (read-only)
    working_dir: /build
    command: ["/bin/sh"]
