version: '3.8'

services:
  package-builder:
    build: .
    #container_name: package_builder
#    environment:
#      DEBUG: 'Y'
    volumes:
      - ./build_packages.sh:/packages/build_packages.sh:ro  # Share script (read-only)
      - ../pkgs:/packages.dist  # Share built packages
      - ../nftlist-lists/data:/packages/data:ro  # Share package content (read-only)
      - ../KEYS/alpine-pkg-SIG.rsa:/home/user/.abuild/SIG-KEY.rsa:ro
      - ../KEYS/alpine-pkg-SIG.rsa.pub:/home/user/.abuild/SIG-KEY.rsa.pub:ro
      # For debugging:
      - ./alpine-sig-key-check.start:/etc/local.d/alpine-sig-key-check.start:ro

    cap_add: ['SYS_ADMIN']
    devices:
      - /dev/fuse

